# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('writer', models.CharField(max_length=100)),
                ('production', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('actor1', models.CharField(max_length=100)),
                ('actor2', models.CharField(max_length=100)),
                ('actor3', models.CharField(max_length=100)),
            ],
        ),
    ]
