# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20170412_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='locations',
            field=models.CharField(default='NA', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='production',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
